#!/usr/bin/env python3
"""Real-time social media monitor for early pump detection on r/wallstreetbets."""

# pylint: disable=duplicate-code

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
import time
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from typing import Any

import requests
from pydantic import BaseModel, Field


STATE_FILE = "/tmp/opencode/wsb_monitor_state.json"
REDDIT_USER_AGENT = "wsb-pump-detect/1.0 (realtime monitor bot)"
WSB_NEW_URL = "https://www.reddit.com/r/wallstreetbets/new.json?limit=100"
POLL_INTERVAL_SECONDS = 300  # 5 minutes
DEFAULT_ITERATIONS = 12  # 1 hour total
VELOCITY_THRESHOLD = 3.0
SENTIMENT_THRESHOLD = 0.6

TICKER_PATTERN = re.compile(r"\$[A-Z]{1,5}|(?<!\$)\b[A-Z]{1,5}\b")

BLACKLIST = {
    "A", "I", "DD", "WSB", "YOLO", "ETF", "IPO", "CEO", "CFO", "USD", "AI",
    "GDP", "PM", "AM", "IT", "AT", "BE", "GO", "ME", "MY", "WE", "HE", "NO",
    "OK", "OR", "SO", "TO", "UP", "US", "FOR", "ALL", "NEW", "ONE", "TWO",
    "BUY", "SELL", "HOLD", "CASH", "VOL", "EPS", "PE", "ATH", "ATL", "FDA",
    "PT", "RH", "TD", "FOMO", "LOL", "IMO", "TLDR", "EDIT", "GAINS", "LOSS",
    "ROPE", "BAN", "MODS", "DFV", "APES", "APE", "SHORT", "SQUEEZE", "MOASS",
    "MOON", "TENDIES", "DIAMOND", "HANDS", "PAPER", "ROCKET", "BAG", "HOLDER",
}

BULLISH_WORDS = {
    "bullish", "moon", "tendies", "calls", "yolo", "squeeze", "breakout",
    "rocket", "long", "buy", "green", "pump", "rip", "higher", "fire",
    "explode", "surge", "rally", "bounce", "uptrend", "accumulation",
}

BEARISH_WORDS = {
    "bearish", "rug", "dump", "baghold", "short", "dead", "rugpull", "exit",
    "sell", "red", "crash", "tank", "dip", "collapse", "plunge", "downtrend",
    "manipulation", "dilution", "bankruptcy", "delist",
}


class DetectionAlert(BaseModel):
    """An alert generated by the pump detection algorithm."""

    ticker: str
    timestamp: str
    mention_velocity: float
    sentiment: float
    mention_count_1h: int
    mention_count_baseline: float
    phase: str = "EARLY PUMP DETECTED"


class MonitorState(BaseModel):
    """Persistent state for the real-time monitor."""

    last_poll_time: str | None = None
    ticker_mention_history: dict[str, list[dict[str, Any]]] = Field(default_factory=dict)
    alerts_since_last_view: list[DetectionAlert] = Field(default_factory=list)
    total_polls: int = 0


def _load_state() -> MonitorState:
    """Load monitor state from disk."""
    os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
    if os.path.exists(STATE_FILE):
        try:
            with open(STATE_FILE, "r", encoding="utf-8") as fh:
                data = json.load(fh)
            return MonitorState(**data)
        except (json.JSONDecodeError, ValueError, TypeError):
            pass
    return MonitorState()


def _save_state(state: MonitorState) -> None:
    """Save monitor state to disk."""
    os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
    with open(STATE_FILE, "w", encoding="utf-8") as fh:
        fh.write(json.dumps(state.model_dump(mode="json"), indent=2, default=str))


def _extract_tickers(text: str) -> list[str]:
    """Extract potential ticker symbols from text."""
    candidates = TICKER_PATTERN.findall(text)
    valid: list[str] = []
    for c in candidates:
        clean = c.lstrip("$").upper()
        if clean in BLACKLIST:
            continue
        if len(clean) < 2:
            continue
        if not clean.isalpha():
            continue
        valid.append(clean)
    return list(set(valid))


def _compute_sentiment(text: str) -> float:
    """Compute a simple sentiment score (0-1) for a text."""
    words = set(text.lower().split())
    bull_count = len(words & BULLISH_WORDS)
    bear_count = len(words & BEARISH_WORDS)
    total = bull_count + bear_count
    if total == 0:
        return 0.5
    return bull_count / total


def _notify_desktop(title: str, body: str) -> bool:
    """Send desktop notification via notify-send if available."""
    if shutil.which("notify-send"):
        os.system(f'notify-send "{title}" "{body}" &')
        return True
    return False


def _poll_wsb(state: MonitorState, verbose: bool = False) -> list[DetectionAlert]:  # pylint: disable=too-many-locals,too-many-statements
    """Poll r/wallstreetbets new posts and detect pump signals."""
    now = datetime.now(timezone.utc)
    now_iso = now.isoformat()
    cutoff_24h = now - timedelta(hours=24)
    cutoff_1h = now - timedelta(hours=1)

    # Fetch new posts
    headers = {"User-Agent": REDDIT_USER_AGENT}
    try:
        resp = requests.get(WSB_NEW_URL, headers=headers, timeout=15)
        resp.raise_for_status()
        data = resp.json()
    except requests.RequestException as exc:
        if verbose:
            print(f"  [ERROR] Failed to fetch WSB: {exc}", file=sys.stderr)
        return []

    children = data.get("data", {}).get("children", [])
    if verbose:
        print(f"  Fetched {len(children)} posts from r/wallstreetbets/new", file=sys.stderr)

    # Extract tickers and timestamps from current poll
    current_mentions: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for child in children:
        post_data = child.get("data", {})
        title = post_data.get("title", "")
        selftext = post_data.get("selftext", "")
        combined = f"{title} {selftext}"
        created_utc = post_data.get("created_utc", 0)
        post_time = datetime.fromtimestamp(created_utc, tz=timezone.utc)

        tickers = _extract_tickers(combined)
        sentiment = _compute_sentiment(combined)

        for ticker in tickers:
            current_mentions[ticker].append({
                "time": post_time.isoformat(),
                "sentiment": round(sentiment, 3),
            })

    # Update state with new mentions
    for ticker, mentions in current_mentions.items():
        if ticker not in state.ticker_mention_history:
            state.ticker_mention_history[ticker] = []
        state.ticker_mention_history[ticker].extend(mentions)

    # Prune old mentions (>24h)
    for ticker in list(state.ticker_mention_history.keys()):
        state.ticker_mention_history[ticker] = [
            m for m in state.ticker_mention_history[ticker]
            if datetime.fromisoformat(m["time"]) > cutoff_24h
        ]
        if not state.ticker_mention_history[ticker]:
            del state.ticker_mention_history[ticker]

    # Detect pump signals
    alerts: list[DetectionAlert] = []
    total_hours = max((now - cutoff_24h).total_seconds() / 3600, 1)

    for ticker, mentions in state.ticker_mention_history.items():
        # Count mentions in last hour
        mentions_1h = [m for m in mentions if datetime.fromisoformat(m["time"]) > cutoff_1h]
        count_1h = len(mentions_1h)

        # Average mentions per hour over 24h
        total_mentions = len(mentions)
        avg_per_hour = total_mentions / total_hours if total_hours > 0 else 0.01

        if avg_per_hour == 0:
            continue

        mention_velocity = count_1h / avg_per_hour if avg_per_hour > 0 else count_1h

        # Average sentiment for last hour mentions
        sentiments = [m["sentiment"] for m in mentions_1h]
        avg_sentiment = sum(sentiments) / len(sentiments) if sentiments else 0.5

        if mention_velocity > VELOCITY_THRESHOLD and avg_sentiment > SENTIMENT_THRESHOLD:
            alert = DetectionAlert(
                ticker=ticker,
                timestamp=now_iso,
                mention_velocity=round(mention_velocity, 2),
                sentiment=round(avg_sentiment, 3),
                mention_count_1h=count_1h,
                mention_count_baseline=round(avg_per_hour, 2),
            )
            alerts.append(alert)
            state.alerts_since_last_view.append(alert)

    # Sort alerts by velocity (most urgent first)
    alerts.sort(key=lambda a: a.mention_velocity, reverse=True)

    state.last_poll_time = now_iso
    state.total_polls += 1

    return alerts


def _print_alert(alert: DetectionAlert) -> None:
    """Print a formatted alert to stdout."""
    print(f"\n  {'=' * 55}")
    print(f"  ⚡ {alert.phase}: ${alert.ticker}")
    print(f"  {'=' * 55}")
    print(f"  Time:              {alert.timestamp}")
    print(f"  Mention Velocity:  {alert.mention_velocity:.1f}x (threshold: {VELOCITY_THRESHOLD}x)")
    print(f"  Sentiment:         {alert.sentiment:.2f} (threshold: {SENTIMENT_THRESHOLD})")
    print(f"  Mentions (1h):     {alert.mention_count_1h}")
    print(f"  Baseline (avg/h):  {alert.mention_count_baseline}")
    print(f"  {'=' * 55}")


def cmd_daemon(args: argparse.Namespace) -> None:
    """Run the monitor in daemon mode (poll every 5 min for N iterations)."""
    iterations = args.iterations or DEFAULT_ITERATIONS
    verbose = args.verbose

    state = _load_state()
    print("WSB Real-Time Pump Monitor")
    print(f"Polling interval: {POLL_INTERVAL_SECONDS // 60} minutes")
    print(f"Iterations:       {iterations} (total: {iterations * POLL_INTERVAL_SECONDS // 60} min)")
    print(f"State file:       {STATE_FILE}")
    print(f"Thresholds:       velocity > {VELOCITY_THRESHOLD}x, sentiment > {SENTIMENT_THRESHOLD}")
    print(f"{'=' * 60}")

    for i in range(1, iterations + 1):
        print(f"\n[Poll {i}/{iterations}] {datetime.now(timezone.utc).strftime('%H:%M:%S UTC')}")
        alerts = _poll_wsb(state, verbose=verbose)

        if alerts:
            print(f"\n  *** {len(alerts)} PUMP ALERT(S) DETECTED ***")
            for alert in alerts:
                _print_alert(alert)
                if args.notify:
                    _notify_desktop(
                        f"WSB Pump Alert: ${alert.ticker}",
                        (f"Velocity: {alert.mention_velocity:.1f}x"
                         f" | Sentiment: {alert.sentiment:.2f}"),
                    )
        else:
            if verbose:
                print("  No pump signals detected.")

        _save_state(state)

        if i < iterations:
            if verbose:
                print(f"\n  Sleeping {POLL_INTERVAL_SECONDS}s until next poll...")
            time.sleep(POLL_INTERVAL_SECONDS)

    print(f"\nMonitoring complete. {state.total_polls} total polls performed.")


def cmd_status(_args: argparse.Namespace) -> None:
    """Show current monitor state."""
    state = _load_state()

    print("WSB Monitor Status")
    print("=" * 60)
    print(f"Last poll:      {state.last_poll_time or 'Never'}")
    print(f"Total polls:    {state.total_polls}")
    print(f"Tracked tickers: {len(state.ticker_mention_history)}")
    print(f"Pending alerts:  {len(state.alerts_since_last_view)}")

    if state.ticker_mention_history:
        print("\nTracked Tickers (last 24h mentions):")
        sorted_tickers = sorted(
            state.ticker_mention_history.items(),  # pylint: disable=no-member
            key=lambda x: len(x[1]),
            reverse=True,
        )[:15]
        for ticker, mentions in sorted_tickers:
            sentiments = [m["sentiment"] for m in mentions]
            avg_sent = sum(sentiments) / len(sentiments) if sentiments else 0
            print(f"  ${ticker:<6} {len(mentions):>4} mentions | avg sentiment: {avg_sent:.2f}")


def cmd_alerts_only(_args: argparse.Namespace) -> None:
    """Show only new alerts since last view, then clear them."""
    state = _load_state()
    alerts = state.alerts_since_last_view

    if not alerts:
        print("No new alerts since last view.")
        return

    print(f"New Alerts ({len(alerts)}):")
    for alert in alerts:
        _print_alert(alert)

    # Clear viewed alerts
    state.alerts_since_last_view = []
    _save_state(state)


def main() -> None:
    """Parse arguments and dispatch to the appropriate command."""
    parser = argparse.ArgumentParser(
        description="Real-time WSB pump detection monitor",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 realtime_monitor.py --daemon
  python3 realtime_monitor.py --daemon --iterations 6 --verbose
  python3 realtime_monitor.py --status
  python3 realtime_monitor.py --alerts-only
        """,
    )
    parser.add_argument("--daemon", "-d", action="store_true",
                        help="Run monitor (poll every 5 min)")
    parser.add_argument("--iterations", "-n", type=int, default=DEFAULT_ITERATIONS,
                        help=f"Number of poll iterations (default: {DEFAULT_ITERATIONS})")
    parser.add_argument("--status", "-s", action="store_true",
                        help="Show current monitor state")
    parser.add_argument("--alerts-only", "-a", action="store_true",
                        help="Show only new alerts since last run")
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="Verbose output including fetch details")
    parser.add_argument("--notify", action="store_true",
                        help="Send desktop notifications for alerts (requires notify-send)")
    args = parser.parse_args()

    if args.daemon:
        cmd_daemon(args)
    elif args.status:
        cmd_status(args)
    elif args.alerts_only:
        cmd_alerts_only(args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
